### ISSUE TITLE
OSError: [Errno 2] No such file or directory while running radosbench  test

### ISSUE THREAD

**Issue by JevonQ** [ceph/cbt#103]
17:56:52 - DEBUG    - cbt      - pdsh -R ssh -w root@ceph echo 3 | sudo tee /proc/sys/vm/drop_caches
^@17:56:53 - ERROR    - cbt      - During tests
Traceback (most recent call last):
  File "./cbt.py", line 71, in main
    b.run()
  File "/root/cbt/benchmark/radosbench.py", line 68, in run
    self._run('write', '%s/write' % self.run_dir, '%s/write' % self.out_dir)
  File "/root/cbt/benchmark/radosbench.py", line 81, in _run
    rados_version_str = subprocess.check_output(["rados", "-v"])
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by JevonQ** [comment]
My environment includes two servers, one is to run cbt and the other is a all-in-one ceph-cluster.
my configuration file is listed as follows,
cluster:
  user: 'root'
  head: "ceph"
  clients: ["ceph"]
  osds: ["ceph"]
  mons:
    ceph:
      a: "192.168.0.18:6789"
  osds_per_node: 1
  fs: 'xfs'
  mkfs_opts: '-f -i size=2048'
  mount_opts: '-o inode64,noatime,logbsize=256k'
  conf_file: '/etc/ceph.conf'
  iterations: 1
  use_existing: True
  clusterid: "ceph"
  tmp_dir: "/tmp/cbt"
  pool_profiles:
    rbd:
      pg_size: 256
      pgp_size: 256
      replication: 1
    rados:
      pg_size: 64
      pgp_size: 64
      replication: 3
benchmarks:
  radosbench:
    time: 300
    write_only: True
    op_size: [4194304]
    concurrent_procs: [1]
    cmd_path: '/usr/bin/rados'
    pool_profile: 'rados'
    ramp: [30]

**Comment by JevonQ** [comment]
Well, just root cause this issue. That's because cbt executes 'rados -v' locally instead of running it on the head node. In my environment, cbt node does not install Ceph, so it continues reporting 'OSError: [Errno 2] No such file or directory'. After I install Ceph, the issue is gone.

However, I still think there is bug here, the command should be executed on the head node, is it correct?

**Comment by JevonQ** [comment]
Send a PR to solve it. https://github.com/ceph/cbt/pull/104
